//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRONTEND.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User1", Namespace="http://schemas.datacontract.org/2004/07/RentEase_Service")]
    [System.SerializableAttribute()]
    public partial class User1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.Admin AdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.Merchant MerchantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.Shopping_cart[] Shopping_cartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string U_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.Admin Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminField, value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.Merchant Merchant {
            get {
                return this.MerchantField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantField, value) != true)) {
                    this.MerchantField = value;
                    this.RaisePropertyChanged("Merchant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.Shopping_cart[] Shopping_carts {
            get {
                return this.Shopping_cartsField;
            }
            set {
                if ((object.ReferenceEquals(this.Shopping_cartsField, value) != true)) {
                    this.Shopping_cartsField = value;
                    this.RaisePropertyChanged("Shopping_carts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string U_Name {
            get {
                return this.U_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.U_NameField, value) != true)) {
                    this.U_NameField = value;
                    this.RaisePropertyChanged("U_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Type {
            get {
                return this.User_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.User_TypeField, value) != true)) {
                    this.User_TypeField = value;
                    this.RaisePropertyChanged("User_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/RentEase_Service")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int A_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.User1 User1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int A_ID {
            get {
                return this.A_IDField;
            }
            set {
                if ((this.A_IDField.Equals(value) != true)) {
                    this.A_IDField = value;
                    this.RaisePropertyChanged("A_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.User1 User1 {
            get {
                return this.User1Field;
            }
            set {
                if ((object.ReferenceEquals(this.User1Field, value) != true)) {
                    this.User1Field = value;
                    this.RaisePropertyChanged("User1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Merchant", Namespace="http://schemas.datacontract.org/2004/07/RentEase_Service")]
    [System.SerializableAttribute()]
    public partial class Merchant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int M_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.Product[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.User1 User1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int M_ID {
            get {
                return this.M_IDField;
            }
            set {
                if ((this.M_IDField.Equals(value) != true)) {
                    this.M_IDField = value;
                    this.RaisePropertyChanged("M_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.User1 User1 {
            get {
                return this.User1Field;
            }
            set {
                if ((object.ReferenceEquals(this.User1Field, value) != true)) {
                    this.User1Field = value;
                    this.RaisePropertyChanged("User1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shopping_cart", Namespace="http://schemas.datacontract.org/2004/07/RentEase_Service")]
    [System.SerializableAttribute()]
    public partial class Shopping_cart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int C_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int P_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.User1 User1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int C_ID {
            get {
                return this.C_IDField;
            }
            set {
                if ((this.C_IDField.Equals(value) != true)) {
                    this.C_IDField = value;
                    this.RaisePropertyChanged("C_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int P_ID {
            get {
                return this.P_IDField;
            }
            set {
                if ((this.P_IDField.Equals(value) != true)) {
                    this.P_IDField = value;
                    this.RaisePropertyChanged("P_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.User1 User1 {
            get {
                return this.User1Field;
            }
            set {
                if ((object.ReferenceEquals(this.User1Field, value) != true)) {
                    this.User1Field = value;
                    this.RaisePropertyChanged("User1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/RentEase_Service")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DecriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.Image[] ImagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int M_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.Merchant MerchantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Registration_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Rental_AgreementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.Shopping_cart[] Shopping_cartsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Available {
            get {
                return this.AvailableField;
            }
            set {
                if ((this.AvailableField.Equals(value) != true)) {
                    this.AvailableField = value;
                    this.RaisePropertyChanged("Available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Decript {
            get {
                return this.DecriptField;
            }
            set {
                if ((object.ReferenceEquals(this.DecriptField, value) != true)) {
                    this.DecriptField = value;
                    this.RaisePropertyChanged("Decript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.Image[] Images {
            get {
                return this.ImagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagesField, value) != true)) {
                    this.ImagesField = value;
                    this.RaisePropertyChanged("Images");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int M_ID {
            get {
                return this.M_IDField;
            }
            set {
                if ((this.M_IDField.Equals(value) != true)) {
                    this.M_IDField = value;
                    this.RaisePropertyChanged("M_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.Merchant Merchant {
            get {
                return this.MerchantField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantField, value) != true)) {
                    this.MerchantField = value;
                    this.RaisePropertyChanged("Merchant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Name {
            get {
                return this.Product_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_NameField, value) != true)) {
                    this.Product_NameField = value;
                    this.RaisePropertyChanged("Product_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Registration_Date {
            get {
                return this.Registration_DateField;
            }
            set {
                if ((this.Registration_DateField.Equals(value) != true)) {
                    this.Registration_DateField = value;
                    this.RaisePropertyChanged("Registration_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rental_Agreement {
            get {
                return this.Rental_AgreementField;
            }
            set {
                if ((object.ReferenceEquals(this.Rental_AgreementField, value) != true)) {
                    this.Rental_AgreementField = value;
                    this.RaisePropertyChanged("Rental_Agreement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.Shopping_cart[] Shopping_carts {
            get {
                return this.Shopping_cartsField;
            }
            set {
                if ((object.ReferenceEquals(this.Shopping_cartsField, value) != true)) {
                    this.Shopping_cartsField = value;
                    this.RaisePropertyChanged("Shopping_carts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Image", Namespace="http://schemas.datacontract.org/2004/07/RentEase_Service")]
    [System.SerializableAttribute()]
    public partial class Image : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Image_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Image_URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int P_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.Product ProductField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Image_ID {
            get {
                return this.Image_IDField;
            }
            set {
                if ((this.Image_IDField.Equals(value) != true)) {
                    this.Image_IDField = value;
                    this.RaisePropertyChanged("Image_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image_URL {
            get {
                return this.Image_URLField;
            }
            set {
                if ((object.ReferenceEquals(this.Image_URLField, value) != true)) {
                    this.Image_URLField = value;
                    this.RaisePropertyChanged("Image_URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int P_ID {
            get {
                return this.P_IDField;
            }
            set {
                if ((this.P_IDField.Equals(value) != true)) {
                    this.P_IDField = value;
                    this.RaisePropertyChanged("P_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductImage", Namespace="http://schemas.datacontract.org/2004/07/RentEase_Service")]
    [System.SerializableAttribute()]
    public partial class ProductImage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.Image ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FRONTEND.ServiceReference1.Product ProductField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.Image Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FRONTEND.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRentEase")]
    public interface IRentEase {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/Login", ReplyAction="http://tempuri.org/IRentEase/LoginResponse")]
        FRONTEND.ServiceReference1.User1 Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/Login", ReplyAction="http://tempuri.org/IRentEase/LoginResponse")]
        System.Threading.Tasks.Task<FRONTEND.ServiceReference1.User1> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/Register", ReplyAction="http://tempuri.org/IRentEase/RegisterResponse")]
        bool Register(string email, string password, string name, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/Register", ReplyAction="http://tempuri.org/IRentEase/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string email, string password, string name, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getProduct", ReplyAction="http://tempuri.org/IRentEase/getProductResponse")]
        FRONTEND.ServiceReference1.ProductImage getProduct(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getProduct", ReplyAction="http://tempuri.org/IRentEase/getProductResponse")]
        System.Threading.Tasks.Task<FRONTEND.ServiceReference1.ProductImage> getProductAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getProducts", ReplyAction="http://tempuri.org/IRentEase/getProductsResponse")]
        FRONTEND.ServiceReference1.ProductImage[] getProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getProducts", ReplyAction="http://tempuri.org/IRentEase/getProductsResponse")]
        System.Threading.Tasks.Task<FRONTEND.ServiceReference1.ProductImage[]> getProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/addToCart", ReplyAction="http://tempuri.org/IRentEase/addToCartResponse")]
        bool addToCart(int UserID, int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/addToCart", ReplyAction="http://tempuri.org/IRentEase/addToCartResponse")]
        System.Threading.Tasks.Task<bool> addToCartAsync(int UserID, int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/removeFromCart", ReplyAction="http://tempuri.org/IRentEase/removeFromCartResponse")]
        bool removeFromCart(int UserID, int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/removeFromCart", ReplyAction="http://tempuri.org/IRentEase/removeFromCartResponse")]
        System.Threading.Tasks.Task<bool> removeFromCartAsync(int UserID, int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getUserCart", ReplyAction="http://tempuri.org/IRentEase/getUserCartResponse")]
        FRONTEND.ServiceReference1.Product[] getUserCart(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getUserCart", ReplyAction="http://tempuri.org/IRentEase/getUserCartResponse")]
        System.Threading.Tasks.Task<FRONTEND.ServiceReference1.Product[]> getUserCartAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getUser", ReplyAction="http://tempuri.org/IRentEase/getUserResponse")]
        FRONTEND.ServiceReference1.User1 getUser(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getUser", ReplyAction="http://tempuri.org/IRentEase/getUserResponse")]
        System.Threading.Tasks.Task<FRONTEND.ServiceReference1.User1> getUserAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/changePassword", ReplyAction="http://tempuri.org/IRentEase/changePasswordResponse")]
        bool changePassword(int ID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/changePassword", ReplyAction="http://tempuri.org/IRentEase/changePasswordResponse")]
        System.Threading.Tasks.Task<bool> changePasswordAsync(int ID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/AddProduct", ReplyAction="http://tempuri.org/IRentEase/AddProductResponse")]
        bool AddProduct(string description, int quantity, decimal price, int merchantID, string[] images);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/AddProduct", ReplyAction="http://tempuri.org/IRentEase/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(string description, int quantity, decimal price, int merchantID, string[] images);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/changeQuantity", ReplyAction="http://tempuri.org/IRentEase/changeQuantityResponse")]
        bool changeQuantity(int ID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/changeQuantity", ReplyAction="http://tempuri.org/IRentEase/changeQuantityResponse")]
        System.Threading.Tasks.Task<bool> changeQuantityAsync(int ID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/changeDescription", ReplyAction="http://tempuri.org/IRentEase/changeDescriptionResponse")]
        bool changeDescription(int ID, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/changeDescription", ReplyAction="http://tempuri.org/IRentEase/changeDescriptionResponse")]
        System.Threading.Tasks.Task<bool> changeDescriptionAsync(int ID, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/changePrice", ReplyAction="http://tempuri.org/IRentEase/changePriceResponse")]
        bool changePrice(int ID, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/changePrice", ReplyAction="http://tempuri.org/IRentEase/changePriceResponse")]
        System.Threading.Tasks.Task<bool> changePriceAsync(int ID, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/removeProduct", ReplyAction="http://tempuri.org/IRentEase/removeProductResponse")]
        bool removeProduct(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/removeProduct", ReplyAction="http://tempuri.org/IRentEase/removeProductResponse")]
        System.Threading.Tasks.Task<bool> removeProductAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/placeOrder", ReplyAction="http://tempuri.org/IRentEase/placeOrderResponse")]
        int placeOrder(int ID, FRONTEND.ServiceReference1.Product[] arrProducts, int[] arrQuantities, int[] arrDurations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/placeOrder", ReplyAction="http://tempuri.org/IRentEase/placeOrderResponse")]
        System.Threading.Tasks.Task<int> placeOrderAsync(int ID, FRONTEND.ServiceReference1.Product[] arrProducts, int[] arrQuantities, int[] arrDurations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getProdsByCat", ReplyAction="http://tempuri.org/IRentEase/getProdsByCatResponse")]
        FRONTEND.ServiceReference1.Product[] getProdsByCat(string Category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getProdsByCat", ReplyAction="http://tempuri.org/IRentEase/getProdsByCatResponse")]
        System.Threading.Tasks.Task<FRONTEND.ServiceReference1.Product[]> getProdsByCatAsync(string Category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getBestProds", ReplyAction="http://tempuri.org/IRentEase/getBestProdsResponse")]
        FRONTEND.ServiceReference1.Product[] getBestProds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getBestProds", ReplyAction="http://tempuri.org/IRentEase/getBestProdsResponse")]
        System.Threading.Tasks.Task<FRONTEND.ServiceReference1.Product[]> getBestProdsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getNewProds", ReplyAction="http://tempuri.org/IRentEase/getNewProdsResponse")]
        FRONTEND.ServiceReference1.Product[] getNewProds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentEase/getNewProds", ReplyAction="http://tempuri.org/IRentEase/getNewProdsResponse")]
        System.Threading.Tasks.Task<FRONTEND.ServiceReference1.Product[]> getNewProdsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentEaseChannel : FRONTEND.ServiceReference1.IRentEase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentEaseClient : System.ServiceModel.ClientBase<FRONTEND.ServiceReference1.IRentEase>, FRONTEND.ServiceReference1.IRentEase {
        
        public RentEaseClient() {
        }
        
        public RentEaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentEaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentEaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentEaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FRONTEND.ServiceReference1.User1 Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<FRONTEND.ServiceReference1.User1> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public bool Register(string email, string password, string name, string surname) {
            return base.Channel.Register(email, password, name, surname);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string email, string password, string name, string surname) {
            return base.Channel.RegisterAsync(email, password, name, surname);
        }
        
        public FRONTEND.ServiceReference1.ProductImage getProduct(int ID) {
            return base.Channel.getProduct(ID);
        }
        
        public System.Threading.Tasks.Task<FRONTEND.ServiceReference1.ProductImage> getProductAsync(int ID) {
            return base.Channel.getProductAsync(ID);
        }
        
        public FRONTEND.ServiceReference1.ProductImage[] getProducts() {
            return base.Channel.getProducts();
        }
        
        public System.Threading.Tasks.Task<FRONTEND.ServiceReference1.ProductImage[]> getProductsAsync() {
            return base.Channel.getProductsAsync();
        }
        
        public bool addToCart(int UserID, int ProductID) {
            return base.Channel.addToCart(UserID, ProductID);
        }
        
        public System.Threading.Tasks.Task<bool> addToCartAsync(int UserID, int ProductID) {
            return base.Channel.addToCartAsync(UserID, ProductID);
        }
        
        public bool removeFromCart(int UserID, int ProductID) {
            return base.Channel.removeFromCart(UserID, ProductID);
        }
        
        public System.Threading.Tasks.Task<bool> removeFromCartAsync(int UserID, int ProductID) {
            return base.Channel.removeFromCartAsync(UserID, ProductID);
        }
        
        public FRONTEND.ServiceReference1.Product[] getUserCart(int ID) {
            return base.Channel.getUserCart(ID);
        }
        
        public System.Threading.Tasks.Task<FRONTEND.ServiceReference1.Product[]> getUserCartAsync(int ID) {
            return base.Channel.getUserCartAsync(ID);
        }
        
        public FRONTEND.ServiceReference1.User1 getUser(int ID) {
            return base.Channel.getUser(ID);
        }
        
        public System.Threading.Tasks.Task<FRONTEND.ServiceReference1.User1> getUserAsync(int ID) {
            return base.Channel.getUserAsync(ID);
        }
        
        public bool changePassword(int ID, string password) {
            return base.Channel.changePassword(ID, password);
        }
        
        public System.Threading.Tasks.Task<bool> changePasswordAsync(int ID, string password) {
            return base.Channel.changePasswordAsync(ID, password);
        }
        
        public bool AddProduct(string description, int quantity, decimal price, int merchantID, string[] images) {
            return base.Channel.AddProduct(description, quantity, price, merchantID, images);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(string description, int quantity, decimal price, int merchantID, string[] images) {
            return base.Channel.AddProductAsync(description, quantity, price, merchantID, images);
        }
        
        public bool changeQuantity(int ID, int quantity) {
            return base.Channel.changeQuantity(ID, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> changeQuantityAsync(int ID, int quantity) {
            return base.Channel.changeQuantityAsync(ID, quantity);
        }
        
        public bool changeDescription(int ID, string description) {
            return base.Channel.changeDescription(ID, description);
        }
        
        public System.Threading.Tasks.Task<bool> changeDescriptionAsync(int ID, string description) {
            return base.Channel.changeDescriptionAsync(ID, description);
        }
        
        public bool changePrice(int ID, double price) {
            return base.Channel.changePrice(ID, price);
        }
        
        public System.Threading.Tasks.Task<bool> changePriceAsync(int ID, double price) {
            return base.Channel.changePriceAsync(ID, price);
        }
        
        public bool removeProduct(int ID) {
            return base.Channel.removeProduct(ID);
        }
        
        public System.Threading.Tasks.Task<bool> removeProductAsync(int ID) {
            return base.Channel.removeProductAsync(ID);
        }
        
        public int placeOrder(int ID, FRONTEND.ServiceReference1.Product[] arrProducts, int[] arrQuantities, int[] arrDurations) {
            return base.Channel.placeOrder(ID, arrProducts, arrQuantities, arrDurations);
        }
        
        public System.Threading.Tasks.Task<int> placeOrderAsync(int ID, FRONTEND.ServiceReference1.Product[] arrProducts, int[] arrQuantities, int[] arrDurations) {
            return base.Channel.placeOrderAsync(ID, arrProducts, arrQuantities, arrDurations);
        }
        
        public FRONTEND.ServiceReference1.Product[] getProdsByCat(string Category) {
            return base.Channel.getProdsByCat(Category);
        }
        
        public System.Threading.Tasks.Task<FRONTEND.ServiceReference1.Product[]> getProdsByCatAsync(string Category) {
            return base.Channel.getProdsByCatAsync(Category);
        }
        
        public FRONTEND.ServiceReference1.Product[] getBestProds() {
            return base.Channel.getBestProds();
        }
        
        public System.Threading.Tasks.Task<FRONTEND.ServiceReference1.Product[]> getBestProdsAsync() {
            return base.Channel.getBestProdsAsync();
        }
        
        public FRONTEND.ServiceReference1.Product[] getNewProds() {
            return base.Channel.getNewProds();
        }
        
        public System.Threading.Tasks.Task<FRONTEND.ServiceReference1.Product[]> getNewProdsAsync() {
            return base.Channel.getNewProdsAsync();
        }
    }
}
